### ISSUE TITLE
Patients's name, appointment and id not showing in the prescription list!

### ISSUE THREAD

**Issue by 34534206** [kishan0725/Hospital-Management-System#1]
When doctor prescribes new patient, patient's name, id and appointment id is not showing the prescription list. It seems there is some bug in this application.

**Comment by kishan0725** [comment]
Thanks for mentioning. Can you show me the screenshot of the issue so that I can know which page are you talking about? In my case, it is working fine. 

![image](https://user-images.githubusercontent.com/36665975/83378633-ed7e9680-a3f6-11ea-87f2-1ed38feab1a0.png)

**Comment by 34534206** [comment]
I tried again adding new patient and gave prescription by doctor, it again shows the same problem. Its in both admin and patient's prescription sections are empty. below is the screen shot of admin's prescription section.
![Untitled](https://user-images.githubusercontent.com/66189342/83379266-d2158a80-a3fa-11ea-9576-5326c9a52d67.png)

**Comment by 34534206** [comment]
i cloned repo again and checked code too, everything seems ok but having the same problem again. Is it because of my server set up system? Do you have any idea, what would be the problem?
Apparently i am also using xampp too. Don't know what went wrong!

**Comment by kishan0725** [comment]
@34534206 Solved it. I've made some changes in the file `prescribe.php`. It was a silly syntactical error. `php` keyword is missing after `<?`. I've attached the changes that I made from the original version of that file.

![image](https://user-images.githubusercontent.com/36665975/83639794-d394ad80-a5c8-11ea-87a5-d7319cded162.png)

**Comment by kishan0725** [comment]
> Thanks for mentioning. Can you show me the screenshot of the issue so that I can know which page are you talking about. In my case, it is working fine.
> 
> ![image](https://user-images.githubusercontent.com/36665975/83378633-ed7e9680-a3f6-11ea-87f2-1ed38feab1a0.png)

@34534206 I ran this one from my deployed project site ([https://kishan0725.000webhostapp.com](https://kishan0725.000webhostapp.com)), which is updated one. So I got correct ouput in this screenshot. After that, I tried once again by cloning this repo, ran the project. Got the same issue that you've faced, found the bug and rectified it. Now this repo is up to date.

**Comment by 34534206** [comment]
I also edited the file you mentioned. Its working now. This is simple application which has nice UI. Thanks!
